apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: football-platform
  namespace: argocd
spec:
  description: GitOps project for the Football Platform app and monitoring stack.
  sourceRepos:
    - https://github.com/dardanrashiti88/football-platform-app.git
  destinations:
    - namespace: football-platform
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources:
    warn: true
