server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location = / {
    try_files /index.html =404;
  }

  location = /mobile {
    return 302 /mobile-version/index.html$is_args$args;
  }

  location = /mobile-player {
    return 302 /mobile-version/player.html$is_args$args;
  }

  location = /mobile-match {
    return 302 /mobile-version/match.html$is_args$args;
  }

  location /api/v1/ {
    proxy_pass http://db-api:3010/api/v1/;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location /api/ {
    proxy_pass http://backend:3002/api/;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location / {
    try_files $uri $uri/ =404;
  }
}
