apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: football-platform-monitoring
  labels:
    app.kubernetes.io/component: monitoring-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: grafana.football-platform.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 3000
    - host: prometheus.football-platform.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus
                port:
                  number: 9090
    - host: alerts.football-platform.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: alertmanager
                port:
                  number: 9093
