apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-data
  labels:
    app.kubernetes.io/component: loki
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
