apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-smtp
  labels:
    app.kubernetes.io/component: alertmanager
stringData:
  SMTP_SMARTHOST: smtp.example.com:587
  SMTP_FROM: alerts@example.com
  SMTP_AUTH_USERNAME: alerts@example.com
  SMTP_AUTH_PASSWORD: change-me-now
  ALERT_EMAIL_TO: alerts@example.com
