apiVersion: v1
kind: Secret
metadata:
  name: grafana-auth
  labels:
    app.kubernetes.io/component: grafana
stringData:
  GF_SECURITY_ADMIN_USER: fod-monitor
  GF_SECURITY_ADMIN_PASSWORD: change-me-now
