apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app.kubernetes.io/component: prometheus
spec:
  selector:
    app.kubernetes.io/component: prometheus
  ports:
    - name: http
      port: 9090
      targetPort: http
