apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: football-platform-production
  namespace: argocd
spec:
  project: football-platform
  source:
    repoURL: https://github.com/dardanrashiti88/football-platform-app.git
    targetRevision: main
    path: k8s/overlays/production
  destination:
    server: https://kubernetes.default.svc
    namespace: football-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
